backend:
  name: github
  repo: casca/casca.dev
  squash_merges: true

site_url: https://casca.dev

publish_mode: editorial_workflow

media_folder: 'static/images'
public_folder: '/images'

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
show_preview_links: true
collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: 'blog/{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', timeFormat: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
