name: Lighthouse Audit

on:
  deployment_status:
    state: success

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: 'https://casca.dev/'
          uploadArtifacts: true
          temporaryPublicStorage: true
