name: Lighthouse Audit

on:
  deployment_status:
    state: success

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Audit URLs using Lighthouse 💡🏡
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: 'https://casca.dev/'
          uploadArtifacts: true
          temporaryPublicStorage: true
