name: Lighthouse Audit

on: deployment_status

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        if: github.event.deployment.environment == 'Production' && github.event.deployment_status.state == 'success'
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Audit URLs using Lighthouse 💡🏡
        id: LHCIAction
        if: github.event.deployment.environment == 'Production' && github.event.deployment_status.state == 'success'
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: 'https://casca.dev'
          uploadArtifacts: true
          temporaryPublicStorage: true
      - run: echo ${{steps.LHCIAction.outputs.resultsPath}}
        if: github.event.deployment.environment == 'Production' && github.event.deployment_status.state == 'success'
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{steps.LHCIAction.outputs.resultsPath}}
